Repository eclipse-uprotocol/up-transport-zenoh-rust, pull requests merged in 2024-08, with the labels that each got.

#64 Bump up-rust to 0.1.5
  Cargo.toml
  tests/l2_rpc.rs
Labels: enhancement

#70 Bump zenoh to 1.0
  Cargo.lock
  Cargo.toml
  config/DEFAULT_CONFIG.json5
  examples/common/mod.rs
  rust-toolchain.toml
  src/lib.rs
  src/rpc.rs
  src/utransport.rs
Labels: breaking change

#74 Add footnote if the PC configuration prevents multicast connections
  README.md
Labels: documentation

#73 Update the CI workflow and add release workflow.
  .github/release.yml
  .github/workflows/README.md
  .github/workflows/check.yaml
  .github/workflows/coverage.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/verify-msrv.yaml
  .github/workflows/x-build.yaml
  Cargo.toml
Labels: enhancement
